name: flutter_graphql_todo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  connectivity_plus: ^2.3.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  go_router: ^4.0.0
  graphql_flutter: ^5.1.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
